import AdminNav from "@/layout/adminPannel/AdminNav";
import Sidebar from "@/layout/adminPannel/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "App (Admin)",
    description: "Generated by News Company",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col h-screen bg-gray-100">

            <AdminNav />

            <div className="flex flex-1 overflow-hidden">

                <Sidebar />

                <main className="flex-1 overflow-y-auto p-6">
                    {children}
                </main>

            </div>
        </div>
    );
}