import Footer from "@/layout/userPannel/Footer";
import Navbar from "@/layout/userPannel/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "User pannel ",
  description: "Generated by News Company",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="min-h-screen flex flex-col">
        <Navbar />

        <main className="flex-1">{children}</main>

        <Footer />
      </div>
    </>
  );
}
